# CREACION_-_USUARIOS
CONSULTA DE BASE DE DATOS
--#USUARIO DUEÑO DE LAS TABLAS
-- USER SQL
CREATE USER "DBAMINVU" IDENTIFIED BY "ADM123vumin45"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "DBAMINVU" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "DBAMINVU" ;
GRANT "RESOURCE" TO "DBAMINVU" ;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY INDEX TO "DBAMINVU" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "DBAMINVU" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "DBAMINVU" WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO "DBAMINVU" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "DBAMINVU" WITH ADMIN OPTION;

------------------------------------------------------------
--#USUARIO DESARROLLADOR N°1
-- USER SQL
CREATE USER "USERDES1" IDENTIFIED BY "DEV1vumin2345"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "USERDES1" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "USERDES1" ;
GRANT "RESOURCE" TO "USERDES1" ;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY PROCEDURE TO "USERDES1" ;
GRANT CREATE ANY VIEW TO "USERDES1" ;
GRANT CREATE ANY MATERIALIZED VIEW TO "USERDES1" ;
GRANT CREATE ANY TRIGGER TO "USERDES1" ;

------------------------------------------------------------
--#USUARIO DESARROLLADOR N°2
-- USER SQL
CREATE USER "USERDES2" IDENTIFIED BY "DEV2vumin1345"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "USERDES2" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "USERDES2" ;
GRANT "RESOURCE" TO "USERDES2" ;

-- SYSTEM PRIVILEGES
GRANT CREATE ANY PROCEDURE TO "USERDES2" ;
GRANT CREATE ANY SEQUENCE TO "USERDES2" ;
GRANT CREATE ANY VIEW TO "USERDES2" ;
GRANT CREATE ANY MATERIALIZED VIEW TO "USERDES2" ;
GRANT CREATE ANY TRIGGER TO "USERDES2" ;

-------------------------------------------------------------
--#USUARIO CONSULTOR 1
-- USER SQL
CREATE USER "CON1" IDENTIFIED BY "USER123minvu"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "CON1" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "CON1";

-- SYSTEM PRIVILEGES

--------------------------------------------------------------
--#USUARIO CONSULTOR 2
-- USER SQL
CREATE USER "CON2" IDENTIFIED BY "USER213minvu"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "CON2" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "CON2";

-- SYSTEM PRIVILEGES

------------------------------------------------------------
--#USUARIO CONSULTOR 3
-- USER SQL
CREATE USER "CON3" IDENTIFIED BY "USER312minvu"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "CON3" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "CON3";

-- SYSTEM PRIVILEGES

--#USUARIO MDY2131_ET_FB_DES
-- USER SQL
CREATE USER "MDY2131_ET_FB_DES" IDENTIFIED BY "mdy2131_et_fb_des"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "MDY2131_ET_FB_DES" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "ROL_CONSULTOR" TO MDY2131_ET_FB_DES;
ALTER USER MDY2131_ET_FB_DES DEFAULT ROLE ROL_CONSULTOR;

-- SYSTEM PRIVILEGES


--#USUARIO MDY2131_ET_FB_CON
-- USER SQL
CREATE USER "MDY2131_ET_FB_CON" IDENTIFIED BY "mdy2131_et_fb_con"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "MDY2131_ET_FB_CON" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "ROL_CONSULTOR" TO MDY2131_ET_FB_CON;
ALTER USER MDY2131_ET_FB_CON DEFAULT ROLE ROL_CONSULTOR;

-- SYSTEM PRIVILEGES


--#ROL CONSULTOR
--ROL_CONSULTOR
CREATE ROLE ROL_CONSULTOR;
GRANT SELECT ON POSTU.POSTULANTE TO ROL_CONSULTOR;
GRANT SELECT ON POSTULANTE_WIN TO ROL_CONSULTOR;

--#CREAR SINONIMOS
CREATE SYNONYM POSTU FOR POSTULANTE;




